### ISSUE TITLE
Security group rule for ingress to mysql lists wrong security group id reference

### ISSUE THREAD

**Issue by isen-ng** [traveloka/terraform-aws-tvlk-bastion#15]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you are interested in working on this issue or have submitted a pull request, please leave a comment!***

***

### Summary

The security group pre-created for mysql does not have any ingress rules because they are mistakenly assigned to the postgres security group.

See https://github.com/traveloka/terraform-aws-tvlk-bastion/blob/master/main.tf#L217

### Module Version

v2.1.0

### Terraform Version and Terraform AWS Provider Version

```
Terraform v0.11.14
+ provider.aws v2.44
```

### Affected Resource(s)

* aws_security_group

### Terraform Configuration Files

```hcl
module "bastion" {
  source = "git@github.com:traveloka/terraform-aws-tvlk-bastion.git?ref=v2.1.0"

  environment    = "${var.environment}"
  product_domain = "${var.product_domain}"
  service_name   = "${var.environment}-${var.product_domain}"

  description   = "Bastion instance for ${var.environment}-${var.product_domain}"
  instance_type = "t2.micro"
  asg_capacity  = 0

  vpc_id      = "${var.vpc_id}"
  subnet_tier = "app"

  ami_owner_account_id = "<redacted>"
}
```

### Expected Behavior

Security group for mysql should have ingress rule for 3306.
Security group for postgres should not have ingress rule for 3306.

### Actual Behavior

Security group for mysql does not have ingress rule for 3306.
Security group for postgres has ingress rule for 3306.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sshvetsov** [comment]
Thanks for reporting this @isen-ng looks like a copy-pasta error. @traveloka/site-infra please take a look.
