### ISSUE TITLE
Install mysql client onto Bastion AMI

### ISSUE THREAD

**Issue by isen-ng** [traveloka/terraform-aws-tvlk-bastion#17]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you are interested in working on this issue or have submitted a pull request, please leave a comment!***

***

### Summary

When we use the site-infra-provided bastion AMI, mysql client is not installed, and therefore, we cannot manage mysql db instances from it. I'm not sure if this is the correct repository to open an issue on, so if this is an incorrect repository, please point me in to the correct repo, and I will open another issue there.

PS, other tools like wget, curl and postgres-client are all installed.

### Module Version

v2.1.1

### Terraform Version and Terraform AWS Provider Version

```
Terraform v0.11.14
+ provider.aws v2.44
```

### Terraform Configuration Files

```hcl
# None
```

### Expected Behavior

The bastion AMI should have mysql client already installed

```
yum install mysql
```

### Actual Behavior

The bastion AMI does not have mysql client installed

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sshvetsov** [comment]
Thanks for opening a ticket @isen-ng . MySQL is not a commonly used database in our organization (we recommend folks to use PostgreSQL, as it is a more feature full database engine), so this is an expected behavior, as we try to install minimum amount of software on our AMIs. However, if you are certain you're going to use MySQL database for your production workloads, I do not see a problem with installing a MySQL client on the bastion AMI.

**Comment by isen-ng** [comment]
> However, if you are certain you're going to use MySQL database for your production workloads,

Yes, we are going to start using aurora serverless in a bid to reduce our costs and aurora serverless only comes in mysql flavours. It would be great if the AMI could have mysql client installed. 

If there is a repo I could send a PR to for you, I would be glad to do that.

**Comment by sshvetsov** [comment]
As a workaround you should be able to install the required software on launch using instance metadata and cloud init, or after launch once connected to the instance using `apt-get install` command.

**Comment by isen-ng** [comment]
Oh thank you!

I will try that, but I'm not sure if that will work because the bastion
instance does not have access to the Internet.

I'll go try that and see what happens.

**Comment by sshvetsov** [comment]
@isen-ng, bastion doesn't have access _from_ the Internet, but it has access _to_ the Internet on port 443. We may need to allow port 80 as well, though.

@SiahaanBernard is port 443 sufficient to download packages from apt repos, or do we also need to open port 80? This would probably be a common ask to install additional tooling.

**Comment by isen-ng** [comment]
Based on my observations, apt-get makes calls to ubuntu archive on http, but I am not sure if they retry on https if the http call doesn't go through

**Comment by sshvetsov** [comment]
Yeah, historically Linux packages have been downloadable through HTTP to allow for easy caching on forward proxies, so I thing port 80 is still default for package managers, meaning we should allow egress on that port.

**Comment by isen-ng** [comment]
Sure thing.
I'll send a PR for this.

**Comment by nin9swells** [comment]
Added to latest bastion AMI.
Please be aware we're changing to Ubuntu 16 and the prefix should be updated accordingly
