### ISSUE TITLE
Security group blocks HTTP egress from the bastion

### ISSUE THREAD

**Issue by sshvetsov** [traveloka/terraform-aws-tvlk-bastion#18]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you are interested in working on this issue or have submitted a pull request, please leave a comment!***

***

### Summary

Since bastion is provisioned using pre-baked AMI into an autoscaling group, it sometimes requires installation of scripts or additional software. To allow installation of deb packages from apt-get repositories, HTTP protocol and port 80 egress needs to be open to 0.0.0.0/0 CIDR.

### Module Version

v2.1.1

### Terraform Version and Terraform AWS Provider Version

```
Terraform v0.11.14
+ provider.aws v2.46.0
```

### Affected Resource(s)

* aws_security_group_rule

### Terraform Configuration Files

```hcl
N/A
```

### Expected Behavior

Bastion security group allows egress on port 80 to 0.0.0.0/0.

### Actual Behavior

Bastion security group doesn't allow egress on port 80 to 0.0.0.0/0.

### Screnshots

N/A

### Steps to Reproduce

1. `terraform apply`
2. run `apt-get update`
3. run `apt-get upgrade`

### Important Factoids

N/A

### References

* #17 Bastion does not allow installation of mysql client

**Comment by sshvetsov** [comment]
@rizkidoank I think we should also bump the tag version to 2.1.2.

**Comment by rizkidoank** [comment]
Yes, I haven't release it yet, currently AFK.
