### ISSUE TITLE
Give bastion role the permissions of arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM

### ISSUE THREAD

**Issue by isen-ng** [traveloka/terraform-aws-tvlk-bastion#21]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### Description

I realized that without giving the bastion VM's role the permissions of `arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM`, the VM will not be "ready for ssm". 

### New or Affected Resource(s)

* aws_instance

### Potential Terraform Configuration Changes

```hcl
module "bastion" {
  source = "git@github.com:traveloka/terraform-aws-tvlk-bastion.git?ref=v2.1.2"

  environment    = "${var.environment}"
  product_domain = "${var.product_domain}"
  service_name   = "${var.environment}-${var.product_domain}"

  description   = "Bastion instance for ${var.environment}-${var.product_domain}"
  instance_type = "t3.nano"
  asg_capacity  = 0

  vpc_id      = "${data.terraform_remote_state.vpc.vpc_id}"
  subnet_tier = "app"

  # this is TSI's account id
  ami_owner_account_id = "<redacted>"
}

# incorporate this in the module, so we don't have to do it ourselves every time.
resource "aws_iam_role_policy_attachment" "ssm" {
  role       = "${module.bastion.instance_role_name}"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
}
```

### References

* #0000

**Comment by isen-ng** [comment]
If you agree that this should be added, I will send a PR.

**Comment by sshvetsov** [comment]
@isen-ng I agree the the bastion instance needs to have minimal permissions to be used with SSM. @SiahaanBernard Frankly, I'm surprised this is not already part of the module in the form of code/documentation/example. I'm not sure if we want to use the managed permissions in this case though, as AWS often doesn't follow PoLP in those.

**Comment by isen-ng** [comment]
If a custom policy is preferred, I can craft an inline policy to attach to the role.
Please advise me on which permissions are required.

We can start from this set (which i copied from `AmazonEC2RoleforSSM`)

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ssm:DescribeAssociation",
                "ssm:GetDeployablePatchSnapshotForInstance",
                "ssm:GetDocument",
                "ssm:DescribeDocument",
                "ssm:GetManifest",
                "ssm:GetParameters",
                "ssm:ListAssociations",
                "ssm:ListInstanceAssociations",
                "ssm:PutInventory",
                "ssm:PutComplianceItems",
                "ssm:PutConfigurePackageResult",
                "ssm:UpdateAssociationStatus",
                "ssm:UpdateInstanceAssociationStatus",
                "ssm:UpdateInstanceInformation"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ssmmessages:CreateControlChannel",
                "ssmmessages:CreateDataChannel",
                "ssmmessages:OpenControlChannel",
                "ssmmessages:OpenDataChannel"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2messages:AcknowledgeMessage",
                "ec2messages:DeleteMessage",
                "ec2messages:FailMessage",
                "ec2messages:GetEndpoint",
                "ec2messages:GetMessages",
                "ec2messages:SendReply"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "cloudwatch:PutMetricData"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstanceStatus"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ds:CreateComputer",
                "ds:DescribeDirectories"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams",
                "logs:PutLogEvents"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:PutObject",
                "s3:GetObject",
                "s3:GetEncryptionConfiguration",
                "s3:AbortMultipartUpload",
                "s3:ListMultipartUploadParts",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by sshvetsov** [comment]
Since we have been deploying bastions and other SSM enabled instances for a while, we already have a minimal SSM policy defined. I'll defer to @SiahaanBernard or another team member to make sure it is referenced and an example on how to apply it to the bastion instance is provided.

**Comment by rafikurnia** [comment]
Hi @isen-ng, thanks for your input. Yes, indeed it is necessary for the permission to be attached to the instance's IAM role for SSM Session Manager to work. 

As what @sshvetsov says, we have a module for the policy and additional resources (i.e., S3 bucket for logging) on https://github.com/traveloka/terraform-aws-session-manager-config. We also put the information about the module our AWS Documentation confluence space. 

However, I agree what is lacking is a reference to the module on this module's documentation. We can add a Prerequisite section to this module's README.md to reference the module.

**Comment by isen-ng** [comment]
Ahh, yes. I did not know that extra repository existed. I have been just added my own policies.

I am curious to why isn't this repository also deployed together as default? I mean, the bastion VM will not work as a SSM jumpbox if this policy is not applied as well. (essentially, I feel that this module is useless without the additional policy)

**Comment by sshvetsov** [comment]
The two are not deployed together because [terraform-aws-session-manager-config](https://github.com/traveloka/terraform-aws-session-manager-config) is a singleton that, by design, needs to be deployed only once per region in a given account. I do completely agree that documentation of this module fails to make any of this clear and needs to be fixed.
