### ISSUE TITLE
Install redis-cli on bastion golden AMI by default

### ISSUE THREAD

**Issue by bobbypriambodo** [traveloka/terraform-aws-tvlk-bastion#23]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### Description
As Redis is one of the most common type of cache used in APR product domain, we occasionally need to access them directly to run some GET commands. Due to the fact that we use Redis with cluster mode and sharding enabled, simple netcat or telnet invocations like what we usually do with Memcached clusters won't work, because a key might not be present with the shard of the instance that receives our command, end hence the instance will [respond with `MOVED`](https://redis.io/topics/cluster-spec#moved-redirection).

The [AWS docs suggests](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/GettingStarted.ConnectToCacheNode.html) to use `redis-cli` to access cluster nodes. The `-c` flag in `redis-cli` will follow those redirection responses to get into the correct shard. It will be convenient if we have them installed on Bastion base golden AMI by default.

Please let me know if you need more information.

### New or Affected Resource(s)

* None

### Potential Terraform Configuration Changes

```hcl
# Copy-paste your Terraform configurations here.
# For large Terraform configs, please use a service like Google Drive and share a link to the ZIP file.
```

### References

* https://redis.io/topics/cluster-spec#moved-redirection
* https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/GettingStarted.ConnectToCacheNode.html

**Comment by bobbypriambodo** [comment]
As a reference, the AWS docs suggests the following invocation to install the tool:

```
$ sudo yum install gcc
$ wget http://download.redis.io/redis-stable.tar.gz
$ tar xvzf redis-stable.tar.gz
$ cd redis-stable
$ make distclean  // Ubuntu systems only
$ make

// Also symlink/move `src/redis-cli` to somewhere in PATH, e.g. /usr/local/bin
```

**Comment by nin9swells** [comment]
Added to latest Bastion AMI.
Please be aware we're changing to Ubuntu 16 and the prefix should be updated accordingly
