### ISSUE TITLE
Add support for additional tags in Bastion ASG instances

### ISSUE THREAD

**Issue by narayananvenk** [traveloka/terraform-aws-tvlk-bastion#25]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### Description

Following [this](https://tvlk.slack.com/archives/C0GLAH89W/p1587711630155400) discussion to add a `Team` tag to resources for teams to track cost per project, creating this issue to support the feature in the Bastion ASG module. 

### New or Affected Resource(s)

* aws-autoscaling_bastion_asg

### Potential Terraform Configuration Changes

Sample change would be [this](https://github.com/traveloka/terraform-aws-tvlk-bastion/commit/9630438f4fae0b878c38f8176d0821bbb5d941be). I can convert this to a PR if the approach is ok. 

```hcl
Terraform Plan changes when a Team tag is passed to this module. 

 ~ module.bastion.module.aws-autoscaling_bastion_asg.aws_autoscaling_group.main
      tags.#:                     "8" => "9"
      tags.8.%:                   "0" => "3"
      tags.8.key:                 "" => "Team"
      tags.8.propagate_at_launch: "" => "1"
      tags.8.value:               "" => "<team-tag>"
```

Please note that the additional tags are applied only to the ASG and not to the security group rules defined in this module. 

### References

* None

**Comment by narayananvenk** [comment]
Requesting a check from @sumodirjo and @rafikurnia (based on recent commit history) as I'm not able to add assignees.

**Comment by nuradhi** [comment]
Hi @narayananvenk , Since it is only applied to ASG tag, I'm fine with it.

**Comment by narayananvenk** [comment]
@nuradhi Thanks, I've updated the variable name based on your suggestion and created a PR for review.
