### ISSUE TITLE
Can we add information about when to use what Subnet tier

### ISSUE THREAD

**Issue by ayusun** [traveloka/terraform-aws-tvlk-bastion#3]
Can you document information about when to use _public_, _data_ and _app_ in subnet tier section?
Thanks

**Comment by sshvetsov** [comment]
Use which subnet tier for what?

**Comment by rafikurnia** [comment]
Hi @ayusun 

We treat the DB bastion as an app (stateless and not publicly accessible), it just makes sense to use app subnet tier. That is why set that as the default value:
https://github.com/traveloka/terraform-aws-tvlk-bastion/blob/48bf429d18ebc42a2bf78dd2b7c9a239e09f0238/variables.tf#L17-L21

Hope that answer your question, I am closing this issue.
