### ISSUE TITLE
Not exactly sure what is the value I should set for `ami_owner_account_id`

### ISSUE THREAD

**Issue by isen-ng** [traveloka/terraform-aws-tvlk-bastion#5]
I'm trying to create a bastion server for my RDS instance using the following repositories
• https://github.com/traveloka/terraform-aws-tvlk-bastion
• https://github.com/traveloka/terraform-aws-rds-postgres

However, the bastion modules requires `ami_owner_account_id` and I don't know where to get this account id.

**Comment by rafikurnia** [comment]
Hi @isen-ng 

`ami_owner_account_id` is the AWS Account ID where we make bastion AMI. Since this module is public, we make them as a variable.

Hope that answers your question
