### ISSUE TITLE
this module depends on traveloka/terraform-aws-iam-role v0.6.0 which forces aws to be version 1.14

### ISSUE THREAD

**Issue by isen-ng** [traveloka/terraform-aws-tvlk-bastion#7]
This module depends on `traveloka/terraform-aws-iam-role.git//modules/instance?ref=v0.6.0`

```
module "bastion" {
  source = "github.com/traveloka/terraform-aws-iam-role.git//modules/instance?ref=v0.6.0"

  service_name = "${var.service_name}"
  cluster_role = "${local.role}"
}
```

And traveloka/terraform-aws-iam-role.git v0.6.0 has this

```
provider "aws" {
  version = "~> 1.14"

  # region is added to prevent consumers getting region prompts (one prompt for each usage)
  region = "${var.region}"
}
```

Which forces anyone to use AWS providers of 1.14.x only.
Versions since v1.0.0 has removed this limitation. I am using aws ~> 2.6

**Comment by rafikurnia** [comment]
Apparently, this issue you raised was addressed by #14
